#spring:
#  data:
#    r2dbc:
#      repositories:
#        enabled: true
#  r2dbc:
#    url: r2dbc:pool:mysql://localhost:3306/wonderdb?zeroDateTimeBehavior=convertToNull&useSSL=false&useServerPrepareStatement=true
#    username: root
#    password: root
#    name: wonderdb